server {
    server_name api.clueroom.xyz;

    client_max_body_size 12M;

    location / {
        proxy_pass http://clueroom_backend;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        add_header X-ClueRoom-Upstream $upstream_addr always;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/api.clueroom.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.clueroom.xyz/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = api.clueroom.xyz) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name api.clueroom.xyz;
    return 404;
}
