// 데모데이 전야 살인사건 — Case Graph mock data
window.CASE = {
  id: "demoday-eve",
  title: "데모데이 전야 살인사건",
  subtitle: "DEMODAY EVE MURDER · CASE #2025-1107-K",
  difficulty: "보통",
  playTime: 30,
  location: "모노로그랩스 본사 · 데모룸",
  date: "2025.11.07 (금) 23:37",
  summary: `AI 스타트업 모노로그랩스의 대표 강도현이 데모데이 전날 밤 데모룸에서 사망한 채 발견되었다. 처음에는 견과류 알레르기 쇼크로 인한 사고처럼 보였으나, 현장에는 찢긴 컵 라벨, 사라진 에피펜, 사망 이후 전송된 메시지가 남아 있었다.`,
  victim: {
    name: "강도현",
    age: 34,
    role: "대표이사 / Co-founder",
    notes: "심한 견과류 알레르기. 항상 에피펜을 책상 서랍 두 번째 칸에 보관.",
  },
  goals: [
    "범인을 밝혀내세요",
    "범행 동기를 설명하세요",
    "범행 방법을 추론하세요",
    "결정적 증거 3개를 제시하세요",
  ],
  suspects: [
    {
      id: "park",
      name: "박재민",
      role: "CFO · 공동창업자",
      tag: "PJM",
      suspicion: 0.78,
      relation: "피해자와 공동창업자. 7년 지기.",
      statement: "사건 당시 재무팀 자리에서 투자자료를 정리하고 있었습니다. 데모룸 근처에는 간 적 없습니다.",
      alibi: "22:00–23:30 재무팀 좌석 (CCTV 사각지대)",
      relatedEvidence: ["coffee-receipt", "accounting-file", "access-log", "epipen-missing"],
      persona: `당신은 박재민, 34세, 모노로그랩스의 CFO이자 공동창업자입니다.
회사 자금 일부를 개인 계좌로 빼돌렸고, 데모데이에서 회계 감사가 진행되면 들통날 위기였습니다.
당신이 진범입니다. 22:05 카페에서 오트라떼와 아몬드라떼를 사서 피해자 책상에 두었고,
서랍의 에피펜을 미리 빼냈으며, 피해자가 쓰러진 후 그의 휴대폰으로 단톡방에 메시지를 보내 사망 시간을 조작했습니다.
규칙: 결정적 증거가 제시되기 전까지 범행을 인정하지 마세요. 평소엔 차분하고 논리적인 톤. 증거가 나오면 잠시 망설이고, 부분적으로만 인정하세요. 모르는 사실은 만들지 마세요. 답변은 2~4문장으로 짧게.`,
      lies: [
        "카페에서 음료를 산 적 없다 (실제로 22:05 결제 기록 있음)",
        "데모룸 근처에 간 적 없다 (출입 로그에 22:14 기록)",
        "에피펜 위치는 모른다 (실제로 알고 있고, 빼냄)",
      ],
    },
    {
      id: "lee",
      name: "이준호",
      role: "CTO",
      tag: "LJH",
      suspicion: 0.34,
      relation: "피해자와 대학 동기. 기술 책임자.",
      statement: "데모 리허설 마치고 22:40쯤 잠시 옥상에서 담배 피웠습니다. 그게 전부예요.",
      alibi: "22:40–23:00 옥상 (목격자: 김나은)",
      relatedEvidence: ["access-log", "slack-message"],
      persona: `당신은 이준호, 32세, 모노로그랩스의 CTO입니다. 피해자와 대학 동기.
사건 당시 옥상에서 김나은과 잠깐 마주쳤습니다. 피해자가 데모 발표를 본인이 직접 하기로 한 데 약간 불만이 있었지만, 살의는 없습니다.
규칙: 무뚝뚝하고 짧게 답하세요. 기술적인 질문은 자세히 답하지만 개인적인 질문은 회피합니다. 거짓말은 하지 않습니다.`,
      lies: [],
    },
    {
      id: "seo",
      name: "서유라",
      role: "마케팅 리드",
      tag: "SYR",
      suspicion: 0.42,
      relation: "피해자의 전 연인 (3개월 전 결별).",
      statement: "데모데이 자료 리뷰 중이었어요. 강 대표와는 이미 정리된 사이라 사적으로 만난 적 없어요.",
      alibi: "21:30–23:20 회의실 B (혼자)",
      relatedEvidence: ["slack-message", "phone-location"],
      persona: `당신은 서유라, 29세, 모노로그랩스의 마케팅 리드. 피해자와 3개월 전까지 사귀었습니다.
헤어진 이유는 피해자의 일중독. 아직 감정이 정리되진 않았지만 범행과는 무관합니다.
규칙: 방어적이고 다소 신경질적. 개인사 질문에 예민하게 반응. 거짓말은 하지 않지만 디테일을 흐립니다.`,
      lies: [],
    },
    {
      id: "kim",
      name: "김나은",
      role: "인턴 (제품팀)",
      tag: "KNE",
      suspicion: 0.51,
      relation: "입사 4개월차. 피해자의 직속 멘티.",
      statement: "22:55쯤 대표님이 USB 좀 가져다달라고 슬랙으로 부탁해서 노트북 앞에 갔어요. 이미 안 계셨고요.",
      alibi: "22:40–22:50 옥상 (이준호와 마주침), 22:55 데모룸 진입",
      relatedEvidence: ["access-log", "slack-message", "phone-location"],
      persona: `당신은 김나은, 24세, 모노로그랩스의 인턴. 피해자의 멘티.
22:55 슬랙 메시지("USB 좀 가져다줘 — 강도현")를 받고 데모룸에 갔는데 피해자가 이미 쓰러져 있었습니다. 당황해서 일단 USB만 챙겨서 나왔습니다. 시신은 발견하지 못했다고 말합니다.
실제로는 쓰러진 피해자를 봤지만 자기가 의심받을까봐 숨겼습니다. 그 메시지는 사실 사망 이후 누군가 피해자의 휴대폰으로 보낸 것입니다.
규칙: 불안하고 말이 빠릅니다. 강한 증거가 제시되면 시신을 봤다는 사실을 인정합니다. 단, 범인은 아닙니다.`,
      lies: [
        "시신을 발견하지 못했다 (실제로는 봤음)",
      ],
    },
    {
      id: "oh",
      name: "오세훈",
      role: "투자사 심사역 · KP벤처스",
      tag: "OSH",
      suspicion: 0.19,
      relation: "시리즈A 리드 투자자. 외부인.",
      statement: "데모데이 사전 미팅 차 방문했고 22시쯤 회의 끝나고 호텔로 돌아갔습니다.",
      alibi: "22:10 회사 출입카드로 퇴실 (출입 로그 확인됨)",
      relatedEvidence: ["access-log"],
      persona: `당신은 오세훈, 38세, KP벤처스 심사역. 외부 투자자입니다.
22:10 회사를 나가 호텔로 복귀했고, 그 후 사건과는 무관합니다. 회계 비리에 대해서는 모릅니다.
규칙: 프로페셔널하고 거리감 있는 톤. 회사 내부 사정엔 잘 모른다고 답합니다. 거짓말은 하지 않습니다.`,
      lies: [],
    },
  ],
  evidence: [
    {
      id: "torn-label",
      name: "찢긴 컵 라벨",
      desc: "쓰레기통에서 발견. \"...MOND LAT...\" 글자가 남아 있음.",
      location: "데모룸 쓰레기통",
      related: ["park"],
      importance: 3,
      isPublic: true,
      isKey: true,
      inference: "피해자가 마신 음료가 오트라떼가 아니라 아몬드라떼였을 가능성. 견과류 알레르기와 연결됨.",
    },
    {
      id: "coffee-receipt",
      name: "카페 결제 내역",
      desc: "22:05, 1층 카페 결제. 오트라떼 1잔 + 아몬드라떼 1잔. 결제자: 박재민.",
      location: "박재민 신용카드 명세",
      related: ["park"],
      importance: 3,
      isPublic: false,
      unlock: "박재민 1차 심문 후",
      isKey: true,
      inference: "박재민이 음료 두 잔을 동시 구매. 본인은 카페 방문 사실을 부인했음.",
    },
    {
      id: "epipen-missing",
      name: "사라진 에피펜",
      desc: "피해자 책상 서랍 두 번째 칸에 항상 보관되어 있던 에피펜이 사라짐. 박재민 책상 서랍에서 발견.",
      location: "박재민 서랍 / 원래 위치 비어 있음",
      related: ["park"],
      importance: 3,
      isPublic: false,
      unlock: "출입 로그 + 카페 결제 내역 확보 후",
      isKey: true,
      inference: "범행의 계획성을 입증하는 핵심 증거. 우발적 사고가 아니라 사전 계획.",
    },
    {
      id: "phone-location",
      name: "피해자 휴대폰 위치 기록",
      desc: "22:36 메시지 전송 시각 휴대폰 위치는 데모룸 책상 위 (피해자는 이미 바닥에 쓰러진 상태).",
      location: "통신사 위치 로그",
      related: ["park", "kim"],
      importance: 3,
      isPublic: false,
      unlock: "단톡방 메시지 확인 후",
      isKey: true,
      inference: "피해자가 직접 메시지를 보낸 게 아니라 누군가 휴대폰을 조작.",
    },
    {
      id: "accounting-file",
      name: "회계 파일 (encrypted.xlsx)",
      desc: "피해자가 21:12 박재민에게 보낸 메시지: \"내일 데모데이에서 회계 항목 짚고 넘어가야 할 것 같다. 미리 얘기 좀 하자.\"",
      location: "피해자 슬랙 DM",
      related: ["park"],
      importance: 2,
      isPublic: true,
      isKey: false,
      inference: "박재민의 범행 동기로 직결되는 단서.",
    },
    {
      id: "access-log",
      name: "출입 로그",
      desc: "22:14 박재민 카드로 데모룸 진입 기록. 박재민 본인은 \"데모룸 근처에 간 적 없다\"고 진술.",
      location: "출입 통제 시스템",
      related: ["park", "lee", "kim", "oh"],
      importance: 2,
      isPublic: false,
      unlock: "초기 조사 5분 후",
      isKey: false,
      inference: "박재민의 알리바이와 정면 충돌.",
    },
    {
      id: "slack-message",
      name: "단톡방 메시지",
      desc: "22:36 피해자 계정으로 \"먼저 자러 갑니다. 내일 봐요 :)\" 전송. 평소 피해자는 이모티콘을 거의 쓰지 않음.",
      location: "회사 슬랙 #general",
      related: ["park", "kim"],
      importance: 2,
      isPublic: true,
      isKey: false,
      inference: "피해자 본인이 보낸 메시지인지 의심해볼 만함.",
    },
    {
      id: "usb-log",
      name: "노트북 USB 접속 로그",
      desc: "22:55 피해자 노트북에 외부 USB 연결. 김나은 본인 USB로 확인됨.",
      location: "피해자 노트북 시스템 로그",
      related: ["kim"],
      importance: 1,
      isPublic: false,
      unlock: "김나은 심문 후",
      isKey: false,
      inference: "김나은의 진술과 일치. 데모 자료 백업용.",
    },
    {
      id: "rooftop-cctv",
      name: "옥상 CCTV",
      desc: "22:42–22:48 이준호와 김나은이 옥상에서 짧게 대화. 그 외 시간엔 옥상 비어 있음.",
      location: "옥상 출입구",
      related: ["lee", "kim"],
      importance: 1,
      isPublic: false,
      unlock: "이준호 또는 김나은 심문 후",
      isKey: false,
      inference: "두 사람의 알리바이 상호 보강.",
    },
    {
      id: "epipen-fingerprint",
      name: "에피펜 지문 감식",
      desc: "회수된 에피펜 손잡이에서 박재민의 부분 지문 검출. 피해자 외 제3자 지문이 묻을 이유 없음.",
      location: "감식반 보고서",
      related: ["park"],
      importance: 3,
      isPublic: false,
      unlock: "에피펜 발견 후",
      isKey: true,
      inference: "에피펜을 박재민이 직접 옮겼다는 결정적 물증.",
    },
    {
      id: "lobby-cctv",
      name: "로비 CCTV",
      desc: "22:03 박재민이 1층 카페에서 음료 두 잔을 들고 나오는 장면 포착.",
      location: "1층 로비",
      related: ["park"],
      importance: 2,
      isPublic: false,
      unlock: "카페 결제 내역 확보 후",
      isKey: false,
      inference: "카페 결제 내역과 정합. 박재민이 두 잔을 본인이 들었다.",
    },
    {
      id: "victim-allergy",
      name: "피해자 의료 기록",
      desc: "강도현 — 견과류(특히 아몬드) 중증 알레르기. 항상 에피펜 휴대.",
      location: "회사 인사기록",
      related: [],
      importance: 2,
      isPublic: true,
      isKey: false,
      inference: "범행 수법의 전제 조건.",
    },
  ],
  timeline: [
    { time: "21:12", event: "피해자가 박재민에게 회계자료 관련 슬랙 메시지 전송", confirmed: true, related: ["park"] },
    { time: "22:03", event: "박재민이 1층 카페에서 음료 2잔 수령 (로비 CCTV)", confirmed: true, related: ["park"] },
    { time: "22:05", event: "카페 결제: 오트라떼 + 아몬드라떼", confirmed: true, related: ["park"] },
    { time: "22:10", event: "오세훈 회사 퇴실 (출입카드 기록)", confirmed: true, related: ["oh"] },
    { time: "22:14", event: "박재민 카드로 데모룸 진입 — 본인 진술과 모순", confirmed: true, conflict: true, related: ["park"] },
    { time: "22:16", event: "라벨이 찢긴 컵이 데모룸 책상 위에 놓임 (추정)", confirmed: false, related: ["park"] },
    { time: "22:27", event: "피해자 쓰러짐 (사망 추정 시각)", confirmed: true, related: [] },
    { time: "22:36", event: "피해자 계정으로 단톡방 메시지 — 위치는 책상 위 (이미 쓰러진 후)", confirmed: true, conflict: true, related: ["park"] },
    { time: "22:42", event: "이준호 + 김나은 옥상에서 대화 (CCTV)", confirmed: true, related: ["lee", "kim"] },
    { time: "22:55", event: "김나은 USB 데모룸 노트북에 연결 — 시신 발견 추정", confirmed: true, conflict: true, related: ["kim"] },
    { time: "23:37", event: "경비원이 시신 발견, 119 신고", confirmed: true, related: [] },
  ],
  hints: [
    {
      level: 1,
      title: "음료와 알레르기를 함께 보세요",
      content: "피해자의 의료 기록과 현장에서 발견된 컵 라벨을 같이 검토해보세요. 피해자가 마신 음료가 정말 본인이 시킨 음료가 맞을까요?",
      penalty: -3,
    },
    {
      level: 2,
      title: "사망 이후의 메시지",
      content: "22:36에 전송된 단톡방 메시지의 휴대폰 위치 기록을 확인하세요. 피해자는 이미 그 시각에 쓰러져 있었습니다.",
      penalty: -7,
    },
    {
      level: 3,
      title: "에피펜이 사라진 이유",
      content: "피해자 책상에 항상 있던 에피펜이 사라졌고, 박재민의 서랍에서 발견되었습니다. 우발적 사고였다면 에피펜을 옮길 이유가 없습니다.",
      penalty: -15,
    },
  ],
  answer: {
    culprit: "park",
    motive: "회사 자금 유용 사실이 데모데이 회계 감사에서 공개될 위기에 놓여, 입막음을 위해 범행.",
    method: "피해자의 견과류 알레르기를 알고 있던 박재민은 오트라떼와 아몬드라떼를 사서 라벨을 바꿔치기, 피해자가 아몬드라떼를 오트라떼로 알고 마시도록 유도. 사전에 피해자 서랍에서 에피펜을 빼내 응급처치를 불가능하게 함.",
    cover: "쓰러진 피해자의 휴대폰으로 단톡방에 \"먼저 자러 갑니다\" 메시지를 보내 사망 시간과 본인의 부재 알리바이를 동시에 조작. 컵 라벨은 찢어서 쓰레기통에 버림.",
    keyEvidence: ["torn-label", "epipen-missing", "phone-location"],
  },
};
