#!/bin/sh

# 현재 브랜치 이름 가져오기 (예: feat/ST-12-test)
BRANCH_NAME=$(git branch --show-current) # 현재 브랜치명을 가져옴

# 브랜치 이름에서 JIRA 이슈 키 추출 (예: ST-12)
JIRA_ISSUE_KEY=$(printf '%s\n' "$BRANCH_NAME" | grep -Eo '[A-Z]+-[0-9]+' | head -n 1)

# 커밋 메시지 파일 경로
COMMIT_MSG_FILE=$1

# 지라 이슈 키가 존재하고, 커밋 메시지에 아직 포함되지 않았다면 커밋 메시지 첫 줄 맨 앞에 "[이슈키] " 추가
if [ -n "$JIRA_ISSUE_KEY" ] && ! grep -Fq "[$JIRA_ISSUE_KEY]" "$COMMIT_MSG_FILE"; then
  sed -i.bak -e "1s/^/[$JIRA_ISSUE_KEY] /" "$COMMIT_MSG_FILE"
fi
